# .github/workflows/test.yml
name: Run Unit Tests # Name of this workflow

on:
  push: # Trigger this workflow on a push event
    branches:
      - test_branch # Specifically when pushing to the 'test_branch'

jobs:
  test: # Define a job named 'test'
    runs-on: ubuntu-latest # Run this job on a fresh Ubuntu virtual machine

    # Add environment variables for this job
    env:
      PYTHONPATH: ${{ github.workspace }} # Sets PYTHONPATH to the root of your repository

    steps:
    - name: Checkout code # Step 1: Get your repository's code
      uses: actions/checkout@v4

    - name: Set up Python environment # Step 2: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Use Python 3.9

    - name: Install dependencies # Step 3: Install required Python packages
      run: |
        python -m pip install --upgrade pip # Upgrade pip
        pip install -r requirements.txt # Install packages from requirements.txt
        pip install pytest # Ensure pytest is installed in the CI environment

    - name: Run Pytest # Step 4: Execute your unit tests
      run: pytest tests/ # Run pytest on the 'tests/' directory